[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "siddhantbhardwaj", email = "bhardwajsiddhant6@gmail.com" }
]
requires-python = ">=3.12"
dependencies = ["mcp[cli]>=1.0.0", "uvicorn>=0.30.0", "motor>=3.5.0"]

[project.scripts]
mcp-server = "mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
